### PR TITLE
fix: do not overwrite customOptions.formats

### PR DESCRIPTION
**Pull request by floratmin**
#### Checklist

- [x] run `npm run test`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

[Issue: Custom format for ajv gets overwritten by ajv-formats](https://github.com/fastify/fastify/issues/5512)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — CHANGES_REQUESTED** [review]
Here is a working solution to your issue:

https://runkit.com/embed/s2wayrdhrxzw

When you set a custom `ajvFormat` plugin, the default one (this one) is replaced by the custom config.

In this case, `ajv-formats` accepts the list of all the formats that must be added (you can get the full list [here](https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts))

```
const fastify = Fastify({
  logger: true,
  ajv: {
    customOptions: {
      formats: {
        date: /foo/,
        foo: /bar/
      }
    },
    plugins: [
      [ajvFormat, [
        // "date",
        "time",
        "date-time",
        "iso-time",
        "iso-date-time",
        "duration",
        "uri",
        "uri-reference",
        "uri-template",
        "url",
        "email",
        "hostname",
        "ipv4",
        "ipv6",
        "regex",
        "uuid",
        "json-pointer",
        "json-pointer-uri-fragment",
        "relative-json-pointer",
        "byte",
        "int32",
        "int64",
        "float",
        "double",
        "password",
        "binary",
      ]
      ]
    ]
  }
});
```

This is documented here:
https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#ajv-plugins

---

Regarding this PR, I would not merge because it is a custom logic tied to the ajv internals.
Since the `ajv-formats` logic here is added as DX stuff, I would prefer a flag to disable it by default, instead of tweaking it.

**Comment by floratmin** [comment]
I solved this issue for me with the current fastify version by using a function with the name `formatsPlugin`. But it seems hacky to me. As an user I would expect that my preferences are not overwritten. On the other side a user who did not realize that their own formats are not used could get a broken system whit this change.

**Comment by Eomm** [comment]
> As an user I would expect that my preferences are not overwritten. On the other side a user who did not realize that their own formats are not used could get a broken system whit this change.

How do you implement the proposed behaviour in pure AJV starting from this use case?

```
const ajv = new AJV({ formats: { date: /foo/ } })
addFormats(ajv)
```

I see these options:

1. configure the `addFormats` properly
2. do not use the `formats` options and write `ajv.addFormat()` method

For this example, I think the best approach to this issue is not to force the `if()do` logic here, but we can do a step forward and:

1. give to the user the possibility to customize the plugin's option (DONE)
1. add a new callback function where the user can run `ajv.addFormat` by themself (MISSING)

My rationale here is that a callback is generic and easy to use compared to check all the conflict that we can face in the ajv's plugins and its configuration.

**Comment by floratmin** [comment]
Thank you very much for your support. But I think that I do not want to implement any design decisions. I can live with my solution.

**Pull request closed without merging**
