### PR TITLE
Updates for fastify@5

### LINKED ISSUE #111: Updating for v5
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm looking to update this repo for v5. https://github.com/fastify/fastify/issues/5116

Changes Needed (Please let me know if anything might be missing)

- Pin tap to 16.3.9
- Update workflows to use v4 (temporarily pointing directly to a git sha)

### PR DESCRIPTION
**Pull request by nrayburn-tech**
- Update workflows to v4
- Update dependencies
- Update readme version compatibility

Fixes #111

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nrayburn-tech** [comment]
Two changes need to be made before merging.

- [ ] Update target branch to `next`
- [ ] Update workflows to use `v4` instead of git sha

**Comment by nrayburn-tech** [comment]
I think that this piece of the readme needs to be updated, but I'm not entirely sure what to put.  Maybe the same as the last line and just bump the `@fastify/ajv-compiler` version?
```
|  v4.x | v8.x | ^4.x |
```

https://github.com/fastify/ajv-compiler/blob/701dc72f187a43a898e2fa0c14732647f8e915b9/README.md?plain=1#L13-L17

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
I only got `3 high severity vulnerabilities`, not sure of much impact this has.

**Review by gurgunday — APPROVED** [review]
lgtm

**Pull request merged**
