### PR TITLE
fix: do not store schema on compile

### PR DESCRIPTION
**Pull request by Eomm**
ref: https://github.com/fastify/fastify/issues/4107

### CODE REVIEW

**Comment by ivan-tymoshenko** [comment]
@Eomm As far as I know, `addUsedSchema` doesn't work with `addSchema` method and we add all schemas using `addSchema`. Can you explain how it works?
https://ajv.js.org/options.html#addusedschema

**Comment by Eomm** [comment]
In this case, the `addSchema` is untouched.
A route's schema is compiled and not added as an external schema.

The origin issue provides the schemas directly to the `compile` function so what is happening:

- the user compiles a schema with the `$id=abc` and it is stored by ajv
- the user compiles a new schema with the same `$id` and this guard is triggered and hide the new schema with the previous one

https://github.com/fastify/ajv-compiler/blob/10879404784f69aa8c5488f77622b52532a28799/index.js#L81

So, from the ajv docs:

> By default methods compile and validate add schemas to the instance if they have $id (or id) property that doesn't start with "#". 

We don't want this to happen because:

- fastify docs say to use `fastify.addSchema` to reuse schema
- route's schema commonly (for me) does not have `$id` fields as it is not mandatory
- users that set route's schema do not reuse them using `$ref`. It would be a hidden feature actually

This fix lets the user to set the same `$id` when a json schema is set directly as the route's schema.
All other checks by using `addSchema` are untouched as said

**Review by ivan-tymoshenko — APPROVED** [review]
So we use the `addSchema` when we want to reuse the schema (have a ref to this schema). And when we use the `compile` method, we compile a validation function but don't store the schema and all nested schemas. If I understand this properly, then it's correct behavior.

We do the same thing in the fast-json-stringify-compiler but use function closure and create a new Ajv instance for each route's schema.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
