### PR TITLE
build(dependabot): add github actions

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
Can the open PRs on https://github.com/fastify/skeleton please be reviewed as well?
If those PRs are merged then hopefully there won't be a need to open PRs like this. 😁

**Comment by mcollina** [comment]
done but there are conflicts now. Anyway, feel free to land these changes yourself after CI pass, there are _too many identical PRs_ for one to approve manually. As long as CI pass, consider yourself good in this org.

**Comment by Fdawgs** [comment]
> 
> 
> done but there are conflicts now. Anyway, feel free to land these changes yourself after CI pass, there are _too many identical PRs_ for one to approve manually. As long as CI pass, consider yourself good in this org.

Thanks @mcollina!
I don't have permissions to land those PRs and quite a few other minor PRs i have open in repos in the org, even though i would consider them plugins (so should be accessible to me in the plugin group, right?).

**Comment by mcollina** [comment]
> I don't have permissions to land those PRs and quite a few other minor PRs i have open in repos in the org, even though i would consider them plugins (so should be accessible to me in the plugin group, right?).

If something is missing, just ask. It's simpler to fix the permission once than to merge a lot of PRs.

**Pull request merged**
